# =============================================================================
# Domain-Profil: CONTOSO
# =============================================================================

[Profile]
DisplayName = Contoso AG

[Collation]
Default = Latin1_General_CI_AS

[SysadminGroups]
Groups = CONTOSO\Rg_SQL_Sysadmin

[Monitoring]
Type = 2

[DiskLayout]
DataDrive    = G
LogDrive     = H
TempDrive    = I
BackupDrive  = F
InstallDrive = C

[SQLSources]
# Pfad zu den SQL-Installationsquellen auf Servern dieser Domain.
# Leer = globaler SourceShare aus settings.ini wird verwendet.
SourcePath =
